import ClientLayoutWrapper from "./ClientLayoutWrapper"
import "./globals.css";
import { Noto_Sans, Open_Sans } from "next/font/google";


export const notoSans = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-noto-sans",
  display: "swap",
});

export const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
  display: "swap",
});

export const metadata = {
  title: "nest-e-commerce",
  description: "Generated by create next app",
  icons: {
    icon: "/nest-icon-transparent.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${notoSans.variable} ${openSans.variable}`}>
      <body className="antialiased">
        <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
      </body>
    </html>
  );
}
